/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface DocumentMetadata {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  data: Json;
  documentId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface Documents {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  id: Generated<string>;
  isFolder: Generated<boolean>;
  parentId: string;
  path: string;
  slug: string;
  title: string;
  typeId: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface DocumentTypes {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  id: Generated<string>;
  isFolder: Generated<boolean>;
  name: string;
  schema: Json;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface DocumentVersions {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  dataSnapshot: Json;
  documentId: string;
  fileUrl: string | null;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
  versionNumber: string;
}

export interface Files {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  id: Generated<string>;
  name: string;
  path: string;
  size: number;
  tags: Generated<Json | null>;
  type: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
  workspaceId: string;
}

export interface Groups {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface Permissions {
  accessType: string;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  documentId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  email: string;
  firstName: string;
  groups: string;
  id: string;
  lastName: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface Workspaces {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface DB {
  documentMetadata: DocumentMetadata;
  documents: Documents;
  documentTypes: DocumentTypes;
  documentVersions: DocumentVersions;
  files: Files;
  groups: Groups;
  permissions: Permissions;
  users: Users;
  workspaces: Workspaces;
}
