/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Documents {
  createdAt: Timestamp;
  createdBy: string;
  id: string;
  name: string;
  path: string;
  size: number;
  type: string;
  updatedAt: Timestamp;
  updatedBy: string;
}

export interface DB {
  documents: Documents;
}
